spring:
  application:
    name: querydsl

  h2:
    console:
      enabled: true        # http://localhost:8080/h2-console

  datasource:
    url: jdbc:h2:tcp://localhost:9092/~/querydsl;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

# java -cp ".\h2-2.3.232.jar" org.h2.tools.Server -tcp -tcpPort 9092 -web -webPort 8082 -ifNotExists -browser